volumes:
  grafana-data:
  influx-data:
  influx-config:

networks:
  edgex-network:
    name: edgex_edgex-network
    driver: bridge

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10mb"
    max-file: "5"

services:
  grafana:
    image: grafana/grafana:10.2.9
    container_name: grafana
    networks:
      edgex-network: null
    ports:
      - "3000:3000"
    restart: always
    volumes:
      # use host timezone
      - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
    logging: *default-logging
  
  influxdb:
    image: influxdb:2.7.10-alpine
    container_name: influxdb
    hostname: influxdb
    networks:
      edgex-network: null
    ports:
      - "8086:8086"
    restart: always
    user: influxdb:influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin-password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: custom-token
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2
    logging: *default-logging

  mqtt-export-broker:
    command:
      - /usr/sbin/mosquitto
      - -c
      - /mosquitto-no-auth.conf
    container_name: edgex-mqtt-export-broker
    hostname: edgex-mqtt-export-broker
    image: eclipse-mosquitto:2.0
    networks:
      edgex-network: null
    ports:
      - mode: ingress
        host_ip: 0.0.0.0
        target: 1883
        published: 1884
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    logging: *default-logging
